-- ─────────────────────────────────────────────────────────────────────────────
-- 006_appointment_tables.sql  –  appointments, appointment_services,
--                                appointment_status_log
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Appointments ─────────────────────────────────────────────────────────────
-- Central booking record. Each row represents a single customer visit.
-- booking_reference is the customer-facing ID (KZB-XXXXX) generated by
-- generate_booking_reference(). Multi-service visits store additional line
-- items in appointment_services.
CREATE TABLE appointments (
  id                  uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  business_id         uuid NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  client_id           uuid REFERENCES clients(id) ON DELETE SET NULL,
  staff_profile_id    uuid REFERENCES staff_profiles(id) ON DELETE SET NULL,
  service_id          uuid REFERENCES services(id) ON DELETE SET NULL,
  status              appointment_status NOT NULL DEFAULT 'pending',
  starts_at           timestamptz NOT NULL,
  ends_at             timestamptz NOT NULL,
  duration_minutes    int NOT NULL,
  price               numeric(10,2) NOT NULL,
  deposit_amount      numeric(10,2) NOT NULL DEFAULT 0,
  booking_source      booking_source NOT NULL DEFAULT 'online',
  booking_reference   text NOT NULL UNIQUE,
  is_walk_in          boolean NOT NULL DEFAULT false,
  notes               text,
  internal_notes      text,
  cancellation_reason text,
  cancelled_at        timestamptz,
  cancelled_by        uuid REFERENCES users(id) ON DELETE SET NULL,
  reminder_sent_at    timestamptz,
  no_show_marked_at   timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_appointments_business_date   ON appointments(business_id, starts_at);
CREATE INDEX idx_appointments_business_client ON appointments(business_id, client_id);
CREATE INDEX idx_appointments_business_staff  ON appointments(business_id, staff_profile_id);
CREATE INDEX idx_appointments_business_status ON appointments(business_id, status);

CREATE TRIGGER trg_appointments_updated_at
  BEFORE UPDATE ON appointments
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ── Appointment Services (line items for multi-service bookings) ──────────────
-- When a customer books more than one service in a single visit, the header
-- row in appointments holds the aggregated totals and the individual services
-- are broken out here with their own staff, price, and time window.
CREATE TABLE appointment_services (
  id                  uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  appointment_id      uuid NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  service_id          uuid NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
  staff_profile_id    uuid REFERENCES staff_profiles(id) ON DELETE SET NULL,
  price               numeric(10,2) NOT NULL,
  duration_minutes    int NOT NULL,
  starts_at           timestamptz,
  ends_at             timestamptz
);

CREATE INDEX idx_appt_services_appointment ON appointment_services(appointment_id);

-- ── Appointment Status Log (full audit trail) ────────────────────────────────
-- Immutable log of every status transition. changed_by is NULL when the
-- transition is system-initiated (e.g. auto-confirm, reminder cron).
CREATE TABLE appointment_status_log (
  id              uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  appointment_id  uuid NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  old_status      appointment_status,
  new_status      appointment_status NOT NULL,
  changed_by      uuid REFERENCES users(id) ON DELETE SET NULL,
  reason          text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_status_log_appt_created ON appointment_status_log(appointment_id, created_at);
