// supabase/functions/admin-monitoring/admin-monitoring.test.ts
//
// S76: by the time this file runs, dozens of other test files in the same
// CI job have already hit real edge functions — each of those calls goes
// through withLogging, which upserts into platform_metrics_hourly via
// record_platform_metric(). So instead of seeding synthetic rows, this test
// asserts against that real, already-accumulated traffic — proving the
// whole pipeline (request → RPC → rollup table → this endpoint) actually
// works end-to-end, not just that the endpoint returns well-formed JSON.
import { assertEquals } from "std/assert"

const BASE = "http://127.0.0.1:54321/functions/v1"
const ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"

const ADMIN_TOKEN = Deno.env.get("TEST_ADMIN_TOKEN") || ""
const OWNER_TOKEN = Deno.env.get("TEST_OWNER_TOKEN") || ""

function call(range?: string, token?: string, origin?: string) {
  const url = new URL(`${BASE}/admin-monitoring`)
  if (range !== undefined) url.searchParams.set("range", range)
  const headers: Record<string, string> = { apikey: ANON_KEY }
  if (token) headers["Authorization"] = `Bearer ${token}`
  if (origin) headers["Origin"] = origin
  return fetch(url.toString(), { headers })
}

Deno.test("admin-monitoring: no Authorization header → 401", async () => {
  const res = await call()
  assertEquals(res.status, 401)
  await res.body?.cancel()
})

Deno.test("admin-monitoring: authenticated but non-admin (seeded owner) → 403", async () => {
  if (!OWNER_TOKEN) return
  const res = await call(undefined, OWNER_TOKEN)
  assertEquals(res.status, 403)
  await res.body?.cancel()
})

Deno.test("admin-monitoring: invalid range → 400", async () => {
  if (!ADMIN_TOKEN) return
  const res = await call("invalid", ADMIN_TOKEN)
  assertEquals(res.status, 400)
  await res.body?.cancel()
})

Deno.test("admin-monitoring: error responses carry the admin app's CORS origin, not the main app's", async () => {
  // Same regression as admin-alert-settings.test.ts's CORS test — this
  // endpoint's error path used the generic serverError(), which falls back
  // to a static Access-Control-Allow-Origin hardcoded to kazione.app when
  // called without the Request object. Real-world symptom that surfaced
  // this: the admin portal's Monitoring/Audit page couldn't read a real
  // 400/500 response at all — "blocked by CORS policy" in the browser.
  if (!ADMIN_TOKEN) return
  const adminOrigin = "https://kazione-booking-admin.pages.dev"
  const res = await call("invalid", ADMIN_TOKEN, adminOrigin)
  assertEquals(res.status, 400)
  assertEquals(res.headers.get("access-control-allow-origin"), adminOrigin)
  await res.body?.cancel()
})

Deno.test("admin-monitoring: platform admin, default range → 200 with well-formed shape", async () => {
  if (!ADMIN_TOKEN) return
  const res = await call(undefined, ADMIN_TOKEN)
  if (res.status !== 200) {
    const body = await res.json().catch(() => null)
    throw new Error(`Expected 200, got ${res.status}: ${JSON.stringify(body)}`)
  }
  const body = await res.json()
  assertEquals(body.range, "24h")
  if (!Array.isArray(body.timeseries)) throw new Error("Expected timeseries to be an array")
  if (!Array.isArray(body.top_errors)) throw new Error("Expected top_errors to be an array")
  if (!Array.isArray(body.health)) throw new Error("Expected health to be an array")
})

Deno.test("admin-monitoring: reflects real traffic already generated by this CI run", async () => {
  if (!ADMIN_TOKEN) return
  // This very request (and every other test file's requests before it)
  // already went through withLogging → record_platform_metric.
  const res = await call("24h", ADMIN_TOKEN)
  assertEquals(res.status, 200)
  const body = await res.json()

  const totalRequests = (body.timeseries as { request_count: number }[])
    .reduce((sum, point) => sum + point.request_count, 0)
  if (totalRequests < 1) {
    throw new Error(
      `Expected at least 1 real request recorded in platform_metrics_hourly by this point in the CI run, got ${totalRequests}. ` +
      `If this fires, either record_platform_metric() isn't being called from withLogging, or the RPC is silently failing.`,
    )
  }
})

Deno.test("admin-monitoring: health includes create-booking (a critical endpoint platform-alert-digest checks)", async () => {
  if (!ADMIN_TOKEN) return
  // Health rows only exist once platform-alert-digest has run at least once
  // this CI run (see platform-alert-digest.test.ts) — safe to no-op if not.
  const res = await call("24h", ADMIN_TOKEN)
  assertEquals(res.status, 200)
  const body = await res.json()
  const health = body.health as { endpoint_name: string; status: string; uptime_pct_24h: number | null; history: unknown[] }[]
  if (health.length === 0) return // digest hasn't run yet in this job — nothing to assert
  const createBooking = health.find((h) => h.endpoint_name === "create-booking")
  if (!createBooking) throw new Error("Expected a health row for create-booking once the digest has run")
  if (!Array.isArray(createBooking.history) || createBooking.history.length === 0) {
    throw new Error("Expected create-booking's health row to include a non-empty history array")
  }
})

Deno.test("admin-monitoring: top_errors entries include recent_errors samples", async () => {
  if (!ADMIN_TOKEN) return
  const res = await call("24h", ADMIN_TOKEN)
  assertEquals(res.status, 200)
  const body = await res.json()
  const topErrors = body.top_errors as { function_name: string; recent_errors: unknown[] }[]
  for (const entry of topErrors) {
    if (!Array.isArray(entry.recent_errors)) {
      throw new Error(`Expected top_errors["${entry.function_name}"].recent_errors to be an array`)
    }
  }
})
